# hoprnet/hopr-workflows/actions/generate-release-notes@generate-release-notes-v1
### Requirements
# - Requires the repository to use Cargo.toml for versioning
# - Requires the repository to use Nix environment
# - Requires the generate-lockfile command to be available in the Nix environment

name: Generate Release Notes
description: Generates release nodes based on PR
inputs:
    branch:
        description: 'Repository branch to generate release notes for'
        required: true
        default: main
    format:
        description: 'Format of the release notes (github, debian, json)'
        required: true
        default: github
    release_notes_file:
        description: 'File to output the release notes to'
        required: false
        default: release_notes.txt
runs:
    using: 'composite'
    steps:
      - name: Generate release notes
        shell: bash
        run: |
            echo "Current directory is $(pwd)"
            echo "Moving to workspace directory ${{ github.workspace }}"
            cd ${{ github.workspace }}
            echo "Current directory is $(pwd)"
            ${{ github.action_path }}/generate-release-notes.sh "${{ inputs.branch }}" "${{ inputs.format }}" "${{ inputs.release_notes_file }}"
        env:
          GH_TOKEN: ${{ github.token }}
        working-directory: ${{ github.workspace }}
