# hoprnet/hopr-workflows/actions/setup-gcp@master
name: 'Setup GCP'
description: 'Install GCP tools and authenticate'
inputs:
    google-credentials:
        description: 'Google credentials taken from secret GOOGLE_HOPRASSOCIATION_CREDENTIALS_REGISTRY'
        required: true
    install-sdk:
        description: 'Install SDK'
        required: false
        default: 'false'
    login-artifact-registry:
        description: 'Authenticate to Artifact Registry'
        required: false
        default: 'false'
    login-gke:
        description: 'Authenticate to GKE'
        required: false
        default: 'false'
    project:
        description: GCP Project name
        required: false
        default: hoprassociation
outputs:
    access_token:
        description: 'GCP Access token'
        value: ${{ steps.auth.outputs.access_token }}
runs:
    using: 'composite'
    steps:
        - name: Set up Google Cloud Credentials
          id: auth
          uses: google-github-actions/auth@v2
          with:
              token_format: 'access_token'
              credentials_json: ${{ inputs.google-credentials }}

        - name: Set up Google Cloud SDK
          if: ${{ inputs.install-sdk == 'true' }}
          uses: google-github-actions/setup-gcloud@v2
          with:
              project_id: ${{ inputs.project }}
              install_components: beta

        - name: Connect to GKE
          uses: google-github-actions/get-gke-credentials@v2
          if: ${{ inputs.login-gke == 'true' }}
          with:
            cluster_name: cluster-${{ inputs.project.replace('hopr', '') }}
            location: europe-west3
            project_id: ${{ inputs.project }}

        - name: Login Google Container Registry
          if: ${{ inputs.login-artifact-registry == 'true' }}
          uses: docker/login-action@v3
          with:
            registry: europe-west3-docker.pkg.dev
            username: oauth2accesstoken
            password: ${{ steps.auth.outputs.access_token }}

