name: Setup GCP
description: Install GCP tools and authenticate
inputs:
    google_credentials:
        description: Google credentials taken from secret GOOGLE_HOPRASSOCIATION_CREDENTIALS_REGISTRY
        required: false
    workload_identity_provider:
        description: Workload Identity Provider
        required: false
    service_account:
        description: Service Account email
        required: false
    install_sdk:
        description: Install SDK
        required: false
        default: 'false'
    login_artifact_registry:
        description: Authenticate to Artifact Registry
        required: false
        default: 'false'
    login_gke:
        description: Authenticate to GKE
        required: false
        default: 'false'
    project:
        description: GCP Project name
        required: false
        default: hoprassociation
    registry:
        description: Artifact Registry URL
        required: false
        default: europe-west3-docker.pkg.dev
outputs:
    access_token:
        description: GCP Access token
        value: ${{ steps.auth.outputs.access_token }}
runs:
    using: composite
    steps:
        - name: Authenticate in Google Cloud using JSON Account Key
          if: inputs.google_credentials != ''
          id: auth_credentials
          uses: google-github-actions/auth@7c6bc770dae815cd3e89ee6cdf493a5fab2cc093 # v3
          with:
              token_format: access_token
              credentials_json: ${{ inputs.google_credentials }}

        - name: Authenticate in Google Cloud using Workload Identity
          id: auth_workload_identity
          if: inputs.workload_identity_provider != '' && inputs.service_account != ''
          uses: google-github-actions/auth@v2
          with:
            workload_identity_provider: ${{ env.WIF_PROVIDER }}
            service_account: ${{ env.WIF_SERVICE_ACCOUNT }}
        - name: Get GCP Access Token
          id: auth
          shell: bash
          run: |
            if [ -n "${{ steps.auth_credentials.outputs.access_token }}" ]; then
              echo "access_token=${{ steps.auth_credentials.outputs.access_token }}" | tee -a "$GITHUB_OUTPUT"
            elif [ -n "${{ steps.auth_workload_identity.outputs.access_token }}" ]; then
              echo "access_token=${{ steps.auth_workload_identity.outputs.access_token }}" | tee -a "$GITHUB_OUTPUT"
            else
              echo "No access token found" >&2
              exit 1
            fi
        - name: Set up Google Cloud SDK
          if: inputs.install_sdk == 'true'
          uses: google-github-actions/setup-gcloud@aa5489c8933f4cc7a4f7d45035b3b1440c9c10db # v3.0.1
          with:
              project_id: ${{ inputs.project }}
              install_components: beta
        - name: Set up Kubernetes cluster variables
          id: variables
          if: inputs.login_gke == 'true'
          shell: bash
          run: |
            CLUSTER_NAME=$(echo "cluster-${{ inputs.project }}" | sed 's/hopr-//g')
            echo "cluster_name=$CLUSTER_NAME" | tee -a "$GITHUB_OUTPUT"
        - name: Connect to GKE
          uses: google-github-actions/get-gke-credentials@3da1e46a907576cefaa90c484278bb5b259dd395 # v3.0.0
          if: inputs.login_gke == 'true'
          with:
            cluster_name: ${{ steps.variables.outputs.cluster_name }}
            location: europe-west3
            project_id: ${{ inputs.project }}
        - name: Login Google Container Registry
          if: inputs.login_artifact_registry == 'true'
          uses: docker/login-action@5e57cd118135c172c3672efd75eb46360885c0ef # v3.6.0
          with:
            registry: ${{ inputs.registry }}
            username: oauth2accesstoken
            password: ${{ steps.auth.outputs.access_token }}
