# hoprnet/hopr-workflows/actions/setup-gcp@gcp-v1
name: Setup GCP
description: Install GCP tools and authenticate
inputs:
    google_credentials:
        description: Google credentials taken from secret GOOGLE_HOPRASSOCIATION_CREDENTIALS_REGISTRY
        required: true
    install_sdk:
        description: Install SDK
        required: false
        default: 'false'
    login_artifact_registry:
        description: Authenticate to Artifact Registry
        required: false
        default: 'false'
    login_gke:
        description: Authenticate to GKE
        required: false
        default: 'false'
    project:
        description: GCP Project name
        required: false
        default: hoprassociation
outputs:
    access_token:
        description: GCP Access token
        value: ${{ steps.auth.outputs.access_token }}
runs:
    using: composite
    steps:
        - name: Set up Google Cloud Credentials
          id: auth
          uses: google-github-actions/auth@v2
          with:
              token_format: access_token
              credentials_json: ${{ inputs.google_credentials }}

        - name: Set up Google Cloud SDK
          if: ${{ inputs.install_sdk == 'true' }}
          uses: google-github-actions/setup-gcloud@v2
          with:
              project_id: ${{ inputs.project }}
              install_components: beta

        - name: Set up GCP
          id: variables
          if: ${{ inputs.login_gke == 'true' }}
          shell: bash
          run: |
            CLUSTER_NAME=$(echo "cluster-${{ inputs.project }}" | sed 's/hopr-//g')
            echo "cluster_name=$CLUSTER_NAME" >> $GITHUB_OUTPUT

        - name: Connect to GKE
          uses: google-github-actions/get-gke-credentials@v2
          if: ${{ inputs.login_gke == 'true' }}
          with:
            cluster_name: ${{ steps.variables.outputs.cluster_name }}
            location: europe-west3
            project_id: ${{ inputs.project }}

        - name: Login Google Container Registry
          if: ${{ inputs.login_artifact_registry == 'true' }}
          uses: docker/login-action@v3
          with:
            registry: europe-west3-docker.pkg.dev
            username: oauth2accesstoken
            password: ${{ steps.auth.outputs.access_token }}

