name: Push Github release
on:
  push:
    tags: '*'
    branches-ignore: '*'

jobs:
  release:
    name: Release github version
    steps:
      - uses: actions/checkout@v2
      - name: Github release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
