name: Upload Artifact Registry
description: Upload Artifact Registry artifacts
inputs:
    source:
        description: Source folder to upload the artifact from
        required: false
        default: ./artifacts
    project:
        description: GCP Project name
        required: false
        default: hoprassociation
    region:
        description: GCP region
        required: false
        default: europe-west3
    repository:
        description: Artifact Registry repository name
        required: false
        default: rust-binaries
    package:
        description: Artifact Registry package name
        required: true
    version:
        description: Artifact version to upload
        required: true
outputs:
    uploaded_files:
        description: Comma-separated list of uploaded files
        value: ${{ steps.artifacts.outputs.uploaded_files }}
runs:
    using: composite
    steps:
      - name: Upload artifacts
        shell: bash
        id: artifacts
        run: |
          files=$(ls -1 ${{ inputs.source }})
          for artifact in $files; do
            gcloud artifacts generic upload \
              --project="${{ inputs.project }}" \
              --location="${{ inputs.region }}" \
              --repository="${{ inputs.repository }}" \
              --package="${{ inputs.package }}" \
              --version="${{ inputs.version }}" \
              --source="${{ inputs.source }}/${artifact}";
          done
          # Create a comma-separated list of uploaded files
          uploaded_files=$(echo "$files" | paste -sd, -)
          echo "uploaded_files=$uploaded_files" | tee -a $GITHUB_OUTPUT
