# hoprnet/hopr-workflows/actions/setup-node-js@master
name: 'Setup NodeJs'
description: 'Setup NodeJS repository'
inputs:
    node-version:
        description: 'Node version to use'
        required: true
runs:
    using: 'composite'
    steps:
        - name: Setup Node.js
          uses: actions/setup-node@v4
          with:
              node-version: ${{ inputs.node-version }}

        - name: Install Yarn
          shell: bash
          run: npm install -g yarn

        - name: Setup Node.js with Yarn
          uses: actions/setup-node@v4
          with:
              node-version: ${{ inputs.node-version }}
              cache: 'yarn'
              cache-dependency-path: ./yarn.lock

        - name: Install dependencies
          shell: bash
          run: yarn --frozen-lockfile
          env:
            NODE_AUTH_TOKEN: foo
