name: Release Version
description: Release Version
inputs:
    file:
        description: File to update version in
        required: true
        default: Cargo.toml
    release_type:
        description: Release type to bump (major, minor, patch, rc)
        required: false
        default: patch
    zulip_api_key:
        description: Zulip API Key for notifications
        required: false
    zulip_email:
        description: Zulip email for notifications
        required: false
    zulip_channel:
        description: Zulip channel for notifications
        required: false
    zulip_topic:
        description: Zulip topic for notifications
        required: false
outputs:
    current_version:
        description: Current released version
        value: ${{ steps.vars.outputs.current_version }}
    bump_version:
        description: Version bumped
        value: ${{ steps.bump.outputs.bump_version }}
runs:
    using: composite
    steps:
      - name: Get current version
        shell: bash
        id: vars
        run: |
          current_version=$(grep -E '^version\s*=' ${{ inputs.file }} | awk -F\" '{print $2}')
          echo "current_version=${current_version}" | tee -a "$GITHUB_OUTPUT"
          if [[ $current_version == *"-rc."* ]]; then
            echo "prerelease=true" | tee -a $GITHUB_OUTPUT
          else
            echo "prerelease=false" | tee -a $GITHUB_OUTPUT
          fi
          repository=${{ github.repository }}
          echo "repository=${repository##*/}" | tee -a $GITHUB_OUTPUT
      - name: Download files
        id: download
        uses: hoprnet/hopr-workflows/actions/download-artifact-registry@ausias/fix-actions
        with:
          package: ${{ steps.vars.outputs.repository }}
          version: ${{ steps.vars.outputs.current_version }}
      - name: Generate Release Notes
        uses: hoprnet/hopr-workflows/actions/generate-release-notes@release-notes-v1
        with:
          source_branch: ${{ github.ref }}
          format: github
      - name: Create Release
        uses: softprops/action-gh-release@a06a81a03ee405af7f2048a818ed3f03bbf83c7b # v2.5.0
        with:
            tag_name: "v${{ steps.vars.outputs.current_version }}"
            prerelease: ${{ steps.vars.outputs.prerelease }}
            name: "v${{ steps.vars.outputs.current_version }}"
            body_path: ./release-notes.txt
            files: ${{ steps.download.outputs.downloaded_files }}
      - name: Bump version
        id: bump
        uses: hoprnet/hopr-workflows/actions/bump-version@bump-version-v1
        with:
          file: ${{ inputs.file }}
          release_type: ${{ inputs.release_type }}
      - name: Prepare notification message
        shell: bash
        if: ${{ inputs.zulip_api_key && inputs.zulip_email && inputs.zulip_channel && inputs.zulip_topic }}
        run: |
          {
            echo "I'm thrilled to inform a new \`${{ github.repository }}\` version \`${{ steps.vars.outputs.current_version }}\` has been released."
            echo ""
            cat ./release-notes.txt
          } > notification_message.txt

          # Store content in environment variable for the Zulip action
          {
            echo "NOTIFICATION_CONTENT<<EOF"
            cat notification_message.txt
            echo "EOF"
          } >> $GITHUB_ENV
      - name: Notify release
        if: ${{ inputs.zulip_api_key && inputs.zulip_email && inputs.zulip_channel && inputs.zulip_topic }}
        uses: zulip/github-actions-zulip/send-message@e4c8f27c732ba9bd98ac6be0583096dea82feea5 # v1.0.2
        with:
          api-key: ${{ inputs.zulip_api_key }}
          email: ${{ inputs.zulip_email }}
          organization-url: "https://hopr.zulipchat.com"
          type: "stream"
          to: ${{ inputs.zulip_channel }}
          topic: ${{ inputs.zulip_topic }}
          content: ${{ env.NOTIFICATION_CONTENT }}
