name: Release Version
description: Release Version
inputs:
    source_branch:
        description: Source branch for release notes
        required: false
        default: main
    file:
        description: File to update version in
        required: true
        default: Cargo.toml
    release_type:
        description: Release type to bump (major, minor, patch, rc)
        required: false
        default: patch
    package_name:
        required: false
        description: "Google artifact registry package name"
    cachix_cache_name:
        required: true
        description: "Cachix cache name to use"
    cachix_auth_token:
        required: true
        description: "Cachix authentication token"
    zulip_api_key:
        description: Zulip API Key for notifications
        required: false
    zulip_email:
        description: Zulip email for notifications
        required: false
    zulip_channel:
        description: Zulip channel for notifications
        required: false
    zulip_topic:
        description: Zulip topic for notifications
        required: false
    gcp_service_account:
        description: GCP Service Account JSON for Artifact Registry access
        required: false
    github_token:
        description: GitHub Token from the Bot with permission to make direct commits into the branch
        required: true
outputs:
    current_version:
        description: Current released version
        value: ${{ steps.version.outputs.current_version }}
    bump_version:
        description: Version bumped
        value: ${{ steps.bump.outputs.bump_version }}
runs:
    using: composite
    steps:
      - name: Checkout hoprnet repository
        uses: actions/checkout@1af3b93b6815bc44a9784bd300feb67ff0d1eeb3 # v6.0.0
        with:
          ref: ${{ inputs.source_branch }}
          fetch-depth: 0
          fetch-tags: true
          token: ${{ inputs.github_token }}
      - name: Get version info
        id: version
        uses: hoprnet/hopr-workflows/actions/set-build-version@set-build-version-v2
        with:
          file: "${{ inputs.file }}"
          version_type: release
      - name: Setup GCP
        if: inputs.gcp_service_account != ''
        id: gcp
        uses: hoprnet/hopr-workflows/actions/setup-gcp@setup-gcp-v2
        with:
          google_credentials: ${{ inputs.gcp_service_account }}
          login_artifact_registry: 'true'
          install_sdk: 'true'
      - name: Setup Nix
        uses: hoprnet/hopr-workflows/actions/setup-nix@setup-nix-v1
        with:
          cachix_cache_name: ${{ inputs.cachix_cache_name }}
          cachix_auth_token: "${{ inputs.cachix_auth_token }}"
      - name: Download binary files
        if: inputs.package_name != ''
        id: download
        uses: hoprnet/hopr-workflows/actions/download-artifact-registry@download-artifact-registry-v1
        with:
          package: ${{ inputs.package_name }}
          version: ${{ steps.version.outputs.current_version }}
      - name: Generate Release Notes
        uses: hoprnet/hopr-workflows/actions/generate-release-notes@generate-release-notes-v1
        with:
          source_branch: ${{ inputs.source_branch }}
          format: github
      - name: Create Release
        uses: softprops/action-gh-release@a06a81a03ee405af7f2048a818ed3f03bbf83c7b # v2.5.0
        with:
            tag_name: "v${{ steps.version.outputs.current_version }}"
            prerelease: ${{ steps.version.outputs.prerelease }}
            name: "v${{ steps.version.outputs.current_version }}"
            body_path: ./release-notes.txt
            files: ${{ steps.download.outputs.downloaded_files || '' }}
      - name: Bump version
        id: bump
        uses: hoprnet/hopr-workflows/actions/bump-version@bump-version-v1
        with:
          file: ${{ inputs.file }}
          release_type: ${{ inputs.release_type }}
      - name: Prepare notification message
        shell: bash
        if: ${{ inputs.zulip_api_key && inputs.zulip_email && inputs.zulip_channel && inputs.zulip_topic }}
        run: |
          {
            echo "I'm thrilled to inform a new \`${{ github.repository }}\` version \`${{ steps.version.outputs.current_version }}\` has been released."
            echo ""
            cat ./release-notes.txt
          } > notification_message.txt

          # Store content in environment variable for the Zulip action
          {
            echo "NOTIFICATION_CONTENT<<EOF"
            cat notification_message.txt
            echo "EOF"
          } >> $GITHUB_ENV
      - name: Notify release
        if: ${{ inputs.zulip_api_key && inputs.zulip_email && inputs.zulip_channel && inputs.zulip_topic }}
        uses: zulip/github-actions-zulip/send-message@e4c8f27c732ba9bd98ac6be0583096dea82feea5 # v1.0.2
        with:
          api-key: ${{ inputs.zulip_api_key }}
          email: ${{ inputs.zulip_email }}
          organization-url: "https://hopr.zulipchat.com"
          type: "stream"
          to: ${{ inputs.zulip_channel }}
          topic: ${{ inputs.zulip_topic }}
          content: ${{ env.NOTIFICATION_CONTENT }}
