# hoprnet/hopr-workflows/actions/set-build-version@set-build-version-v1
### Requirements
# - Requires the repository to use Cargo.toml for versioning
# - Requires the repository to use Nix environment
# - Requires the generate-lockfile command to be available in the Nix environment

name: 'Setup Version'
description: 'Setup Version'
inputs:
    file:
        description: 'File to update version in'
        required: true
        default: Cargo.toml
    version_type:
        description: 'Version type to bump (commit, pr, release)'
        required: true
outputs:
    current_version:
        description: 'Current version extracted from file'
        value: ${{ steps.versions.outputs.current_version }}
    commit_version:
        description: 'Version with commit hash'
        value: ${{ steps.versions.outputs.commit_version }}
    pr_version:
        description: 'Version with pull request number'
        value: ${{ steps.versions.outputs.pr_version }}
    release_version:
        description: 'Release version'
        value: ${{ steps.versions.outputs.release_version }}
    build_version:
        description: 'Build version based on version type'
        value: ${{ steps.versions.outputs.build_version }}
    docker_version:
        description: 'Docker compatible version'
        value: ${{ steps.versions.outputs.docker_version }}
runs:
    using: 'composite'
    steps:
      - name: Gather versions
        shell: bash
        id: versions
        run: |
          current_version=$(grep -E '^version\s*=' ${{ inputs.file }} | awk -F\" '{print $2}')
          echo "current_version=${current_version}" | tee -a "$GITHUB_OUTPUT"
          echo "commit_version=$current_version+commit.$(git rev-parse --short HEAD)" | tee -a "$GITHUB_OUTPUT"
          echo "pr_version=$current_version+pr.${{ github.event.pull_request.number }}" | tee -a "$GITHUB_OUTPUT"
          echo "release_version=$current_version" | tee -a "$GITHUB_OUTPUT"
          if [[ "${{ inputs.version_type }}" == "commit" ]]; then
            build_version=${commit_version}
          elif [[ "${{ inputs.version_type }}" == "pr" ]]; then
            build_version=${pr_version}
          elif [[ "${{ inputs.version_type }}" == "release" ]]; then
            build_version=${release_version}
          else
            echo "Invalid version type"
            echo "Parameter version_type must be one of the following:"
            echo "- 'commit': To set version with commit hash"
            echo "- 'pr': To set version with pull request number"
            echo "- 'release': To set version for release"
            exit 1
          fi
          echo "build_version=${build_version}" | tee -a "$GITHUB_OUTPUT"
          echo "docker_version=${build_version/+/-}}" | tee -a "$GITHUB_OUTPUT"
      - name: Update build version
        shell: bash
        run: |
          sed -i.bak -E "s/(^version = \")([0-9]+\.[0-9]+\.[0-9]+)(\")/\1${{ steps.versions.outputs.build_version}}\3/" ${{ inputs.file }}
          nix develop -c cargo generate-lockfile
          rm "${{ inputs.file }}.bak"
