name: 'Setup Version'
description: 'Setup Version'
inputs:
    file:
        description: 'File to update version in'
        required: true
        default: Cargo.toml
    version_type:
        description: 'Version type to bump (commit, pr, release)'
        required: true
    architecture:
        description: 'Target architecture for the docker image'
        required: false
        default: x86_64-linux
outputs:
    current_version:
        description: 'Current version extracted from file'
        value: ${{ steps.versions.outputs.current_version }}
    commit_version:
        description: 'Version with commit hash'
        value: ${{ steps.versions.outputs.commit_version }}
    debug_version:
        description: 'Debug version with commit hash'
        value: ${{ steps.versions.outputs.debug_version }}
    pr_version:
        description: 'Version with pull request number'
        value: ${{ steps.versions.outputs.pr_version }}
    release_version:
        description: 'Release version'
        value: ${{ steps.versions.outputs.release_version }}
    prerelease:
        description: 'Whether the version is a prerelease'
        value: ${{ steps.versions.outputs.prerelease }}
    build_version:
        description: 'Build version based on version type'
        value: ${{ steps.versions.outputs.build_version }}
    docker_build_version:
        description: 'Docker compatible version'
        value: ${{ steps.versions.outputs.docker_build_version }}
    docker_debug_version:
        description: 'Docker compatible debug version'
        value: ${{ steps.versions.outputs.docker_debug_version }}
    docker_build_version_platform:
        description: 'Docker compatible version with platform suffix'
        value: ${{ steps.versions.outputs.docker_build_version_platform }}
    docker_debug_version_platform:
        description: 'Docker compatible debug version with platform suffix'
        value: ${{ steps.versions.outputs.docker_debug_version_platform }}
    docker_platform:
        description: 'Docker platform based on architecture'
        value: ${{ steps.versions.outputs.docker_platform }}
    publish_artifact_registry:
        description: 'Whether to publish the artifact in the Google Artifact registry'
        value: ${{ steps.versions.outputs.publish_artifact_registry }}
    publish_github_release:
        description: 'Whether to publish the artifact in the GitHub Release'
        value: ${{ steps.versions.outputs.publish_github_release }}
    deploy_staging:
        description: 'Whether to deploy to staging environment'
        value: ${{ steps.versions.outputs.deploy_staging }}
runs:
    using: 'composite'
    steps:
      - name: Get PR labels
        uses: joerick/pr-labels-action@0543b277721e852d821c6738d449f2f4dea03d5f # v1.0.9
      - name: Gather versions
        shell: bash
        id: versions
        run: |
          echo "Gathering version from ${{ inputs.file }} and setting build version type to '${{ inputs.version_type }}'"
          if [[ "${{ inputs.file }}" =~ ^.*\.toml$ ]]; then
            current_version=$(grep -E '^version\s*=' ${{ inputs.file }} | awk -F\" '{print $2}')
          elif [[ "${{ inputs.file }}" =~ ^.*\.json$ ]]; then
            current_version=$(jq -r '.version' ${{ inputs.file }})
          else
            echo "Unsupported file type: ${{ inputs.file }}"
            exit 1
          fi
          commit_version="$current_version+commit.$(git rev-parse --short HEAD)"
          pr_version="$current_version+pr.${{ github.event.pull_request.number }}"
          release_version="$current_version"
          publish_artifact_registry=false
          publish_github_release=false
          deploy_staging=false
          prerelease=false
          if [[ "${{ inputs.version_type }}" == "commit" ]]; then
            build_version=${commit_version}
            if [ "${GITHUB_PR_LABEL_PUBLISH_BINARIES:-0}" == '1' ]; then
              publish_artifact_registry=true
            fi
            # The applications using the `deploy-staging` label will be deployed on PR commits to staging
            if [[ "${GITHUB_PR_LABEL_DEPLOY_STAGING:-0}" == '1' ]]; then
              deploy_staging=true
            fi
          elif [[ "${{ inputs.version_type }}" == "pr" ]]; then
            build_version=${pr_version}
            publish_artifact_registry=true
          elif [[ "${{ inputs.version_type }}" == "release" ]]; then
            build_version=${release_version}
            publish_github_release=true
            publish_artifact_registry=true
            if [[ $current_version == *"-rc."* ]]; then
              echo "prerelease=true"
            fi
          else
            echo "Invalid version type"
            echo "Parameter version_type must be one of the following:"
            echo "- 'commit': To set version with commit hash"
            echo "- 'pr': To set version with pull request number"
            echo "- 'release': To set version for release"
            exit 1
          fi

          ## Debug build flavor
          if [[ "${{ inputs.version_type }}" == "commit" ]] && [[ "${GITHUB_PR_LABEL_BUILD_FLAVOR_DEBUG:-0}" == '1' ]]; then
              debug_version="$current_version+debug.$(git rev-parse --short HEAD)"
              docker_debug_version=${debug_version/+/-}
              if [[ "${{ inputs.architecture }}" == "aarch64-linux" ]]; then
                docker_debug_version_platform="${docker_debug_version}-linux-arm64"
              elif [[ "${{ inputs.architecture }}" == "x86_64-linux" ]]; then
                docker_debug_version_platform="${docker_debug_version}-linux-amd64"
              fi
              echo "debug_version=${debug_version}" | tee -a "$GITHUB_OUTPUT"
              echo "docker_debug_version=${docker_debug_version}" | tee -a "$GITHUB_OUTPUT"
              echo "docker_debug_version_platform=${docker_debug_version_platform}" | tee -a "$GITHUB_OUTPUT"
          fi

          # Generate Docker compatible version
          docker_build_version=${build_version/+/-}
          if [[ "${{ inputs.architecture }}" == "aarch64-linux" ]]; then
            docker_build_version_platform="${docker_build_version}-linux-arm64"
            docker_platform="linux-arm64"
          elif [[ "${{ inputs.architecture }}" == "x86_64-linux" ]]; then
            docker_build_version_platform="${docker_build_version}-linux-amd64"
            docker_platform="linux-amd64"
          else
            echo "Unsupported architecture: ${{ inputs.architecture }}"
          fi
          echo "current_version=${current_version}" | tee -a "$GITHUB_OUTPUT"
          echo "commit_version=${commit_version}" | tee -a "$GITHUB_OUTPUT"
          echo "pr_version=${pr_version}" | tee -a "$GITHUB_OUTPUT"
          echo "release_version=${release_version}" | tee -a "$GITHUB_OUTPUT"
          echo "prerelease=${prerelease}" | tee -a "$GITHUB_OUTPUT"
          echo "build_version=${build_version}" | tee -a "$GITHUB_OUTPUT"
          echo "docker_build_version=${docker_build_version}" | tee -a "$GITHUB_OUTPUT"
          echo "docker_build_version_platform=${docker_build_version_platform}" | tee -a "$GITHUB_OUTPUT"
          echo "docker_platform=${docker_platform}" | tee -a "$GITHUB_OUTPUT"
          echo "publish_artifact_registry=${publish_artifact_registry}" | tee -a "$GITHUB_OUTPUT"
          echo "publish_github_release=${publish_github_release}" | tee -a "$GITHUB_OUTPUT"
          echo "deploy_staging=${deploy_staging}" | tee -a "$GITHUB_OUTPUT"
      - name: Update build version
        # Equivalent to:  inputs.version_type != 'release'
        if: steps.versions.outputs.current_version != steps.versions.outputs.build_version
        shell: bash
        run: |
          if [[ "${{ inputs.file }}" =~ .*\.toml$ ]]; then
            sed -i.bak -E "s/(^version = \")([0-9]+\.[0-9]+\.[0-9]+)(-rc\.[0-9]+)?(\+.*)?(\")/\1${{ steps.versions.outputs.build_version}}\5/" ${{ inputs.file }}
            rm "${{ inputs.file }}.bak"
            if [[ "${{ inputs.file }}" =~ .*Cargo\.toml$ ]]; then
              echo "Regenerating Cargo.lock file"
              nix develop --command cargo generate-lockfile
            fi
          elif [[ "${{ inputs.file }}" =~ ^.*\.json$ ]]; then
            jq --arg build_version "${{ steps.versions.outputs.build_version }}" '.version = $build_version' ${{ inputs.file }} > "${{ inputs.file }}.tmp"
            mv "${{ inputs.file }}.tmp" ${{ inputs.file }}
          fi
