# hoprnet/hopr-workflows/actions/set-build-version@build-version-v1
### Requirements
# - Requires the repository to use Cargo.toml for versioning
# - Requires the repository to use Nix environment
# - Requires the generate-lockfile command to be available in the Nix environment

name: 'Setup Version'
description: 'Setup Version'
inputs:
    file:
        description: 'File to update version in'
        required: true
        default: Cargo.toml
    version_type:
        description: 'Version type to bump (commit, pr, release)'
        required: true
outputs:
    current_version:
        description: 'Current version extracted from file'
        value: ${{ steps.versions.outputs.current_version }}
    commit_version:
        description: 'Version with commit hash'
        value: ${{ steps.versions.outputs.commit_version }}
    pr_version:
        description: 'Version with pull request number'
        value: ${{ steps.versions.outputs.pr_version }}
    release_version:
        description: 'Release version'
        value: ${{ steps.versions.outputs.release_version }}
    build_version:
        description: 'Build version based on version type'
        value: ${{ steps.versions.outputs.build_version }}
    docker_version:
        description: 'Docker compatible version'
        value: ${{ steps.versions.outputs.docker_version }}
    publish_workflow_run:
        description: 'Whether to publish the artifact in the workflow run'
        value: ${{ steps.versions.outputs.publish_workflow_run }}
    publish_artifact_registry:
        description: 'Whether to publish the artifact in the Google Artifact registry'
        value: ${{ steps.versions.outputs.publish_artifact_registry }}
    publish_github_release:
        description: 'Whether to publish the artifact in the GitHub Release'
        value: ${{ steps.versions.outputs.publish_github_release }}

runs:
    using: 'composite'
    steps:
      - name: Get PR labels
        uses: joerick/pr-labels-action@0543b277721e852d821c6738d449f2f4dea03d5f # v1.0.9
      - name: Gather versions
        shell: bash
        id: versions
        run: |
          set -x
          echo "Gathering version from ${{ inputs.file }} and setting build version type to '${{ inputs.version_type }}'"
          current_version=$(grep -E '^version\s*=' ${{ inputs.file }} | awk -F\" '{print $2}')
          commit_version="$current_version+commit.$(git rev-parse --short HEAD)"
          pr_version="$current_version+pr.${{ github.event.pull_request.number }}"
          release_version="$current_version"
          publish_workflow_run=false
          publish_artifact_registry=false
          publish_github_release=false
          if [[ "${{ inputs.version_type }}" == "commit" ]]; then
            build_version=${commit_version}
            if [ "${GITHUB_PR_LABEL_PUBLISH_BINARIES:-0}" == '1' ]; then
              publish_artifact_registry=true
            else
              publish_workflow_run=true
            fi
          elif [[ "${{ inputs.version_type }}" == "pr" ]]; then
            build_version=${pr_version}
            publish_artifact_registry=true
          elif [[ "${{ inputs.version_type }}" == "release" ]]; then
            build_version=${release_version}
            publish_github_release=true
            publish_artifact_registry=true
          else
            echo "Invalid version type"
            echo "Parameter version_type must be one of the following:"
            echo "- 'commit': To set version with commit hash"
            echo "- 'pr': To set version with pull request number"
            echo "- 'release': To set version for release"
            exit 1
          fi
          echo "current_version=${current_version}" | tee -a "$GITHUB_OUTPUT"
          echo "commit_version=${commit_version}" | tee -a "$GITHUB_OUTPUT"
          echo "pr_version=${pr_version}" | tee -a "$GITHUB_OUTPUT"
          echo "release_version=${release_version}" | tee -a "$GITHUB_OUTPUT"
          echo "build_version=${build_version}" | tee -a "$GITHUB_OUTPUT"
          echo "docker_version=${build_version/+/-}" | tee -a "$GITHUB_OUTPUT"
          echo "publish_workflow_run=${publish_workflow_run}" | tee -a "$GITHUB_OUTPUT"
          echo "publish_artifact_registry=${publish_artifact_registry}" | tee -a "$GITHUB_OUTPUT"
          echo "publish_github_release=${publish_github_release}" | tee -a "$GITHUB_OUTPUT"
      - name: Update build version
        shell: bash
        run: |
          sed -i.bak -E "s/(^version = \")([0-9]+\.[0-9]+\.[0-9]+)(\")/\1${{ steps.versions.outputs.build_version}}\3/" ${{ inputs.file }}
          if [[ "${{ inputs.file }}" =~ .*Cargo\.toml$ ]]; then
            nix develop -c cargo generate-lockfile
          fi
          rm "${{ inputs.file }}.bak"
