# hoprnet/hopr-workflows/actions/bump-version@bump-version-v1
### Requirements
# - Requires the repository to use Cargo.toml for versioning
# - Requires the repository to use Nix environment
# - Requires the generate-lockfile command to be available in the Nix environment

name: Bump Version
description: Bump Version
inputs:
    file:
        description: File to update version in
        required: true
        default: Cargo.toml
    release_type:
        description: Release type to bump (major, minor, patch)
        required: false
        default: patch
outputs:
    current_version:
        description: Current version extracted from file
        value: ${{ steps.versions.outputs.current_version }}
    bump_version:
        description: Version bumped
        value: ${{ steps.versions.outputs.bump_version }}
runs:
    using: composite
    steps:
      - name: Bump version
        shell: bash
        id: versions
        run: |
          current_version=$(grep -E '^version\s*=' ${{ inputs.file }} | awk -F\" '{print $2}')
          echo "current_version=${current_version}" | tee -a "$GITHUB_OUTPUT"
          # Extract parts without IFS or read
          IFS='.' read -r major_version minor_version patch_version <<< "${current_version}"
          echo "Current version ${major_version}.${minor_version}.${patch_version}"
          # Bump the appropriate part
          echo "Bumping ${{ inputs.release_type }} version"
          case "${{ inputs.release_type }}" in
              major)
                  major_version=$((major_version+1))
                  minor_version=0
                  patch_version=0
                  ;;
              minor)
                  minor_version=$((minor_version+1))
                  patch_version=0
                  ;;
              patch)
                  patch_version=$((patch_version+1))
                  ;;
              *)
                  echo "Invalid release type ${{ inputs.release_type }}"
                  exit 1
                  ;;
          esac
          echo "New version: ${major_version}.${minor_version}.${patch_version}"
          bump_version="${major_version}.${minor_version}.${patch_version}"

          # Update the version in the specified file
          # capture group 1: version = "
          # capture group 2: the version number
          # capture group 3: "
          sed -i.bak -E "s/(^version = \")([0-9]+\.[0-9]+\.[0-9]+)(\")/\1${bump_version}\3/" ${{ inputs.file }}
          rm ${{ inputs.file }}.bak
          if [[ "${{ inputs.file }}" =~ .*Cargo\.toml$ ]]; then
            nix develop --command cargo generate-lockfile
          fi
          echo "bump_version=${bump_version}" | tee -a "$GITHUB_OUTPUT"
          lock_file=$(echo "${{ inputs.file }}" | sed 's/toml/lock/')
          echo "lock_file=${lock_file}" | tee -a "$GITHUB_OUTPUT"
      - uses: EndBug/add-and-commit@a94899bca583c204427a224a7af87c02f9b325d5 # v9.1.4
        with:
          add: '["${{ inputs.file }}", "${{ steps.versions.outputs.lock_file }}"]'
          new_branch: main
          message: "Bump to version ${{ steps.versions.outputs.bump_version }}"
          pathspec_error_handling: ignore
