# hoprnet/hopr-workflows/actions/setup-nix@nix-v1
name: 'Setup Nix'
description: 'Setup Nix environment'
inputs:
    cache:
        description: 'Name of the Cachix cache to use'
        required: true
    authToken:
        description: 'Cachix authentication token'
        required: false
    nix_path:
        description: 'Nix path to use'
        required: false
        default: 'nixpkgs=channel:nixos-24.05'
runs:
    using: 'composite'
    steps:
      - name: Install Nix
        uses: cachix/install-nix-action@v31
        with:
          nix_path: ${{ inputs.nix_path }}
      - name: Use Nix Cache
        uses: cachix/cachix-action@v16
        with:
          name: ${{ inputs.cache }}
          authToken: ${{ inputs.authToken }}
        env:
          USER: runner

