# hoprnet/hopr-workflows/actions/publish-gcp-artifact@master
name: 'Publish GCP Artifact'
description: 'Publish an artifact with its signature and hash to Artifact Registry'
inputs:
    artifact-path:
        description: 'Path to the artifact to be published'
        required: true
    artifact-version:
        description: 'GCP Artifact Registry version'
        required: true
    gcp-project:
        description: GCP Project name
        required: true
    registry-repository:
        description: 'GCP Artifact Registry repository name'
        required: true
    registry-location:
        description: 'GCP Artifact Registry location (e.g., europe-west3)'
        required: true
    registry-package:
        description: 'GCP Artifact Registry package name'
        required: true
    create-signatures:
        description: 'Create signatures for the artifacts'
        required: true
        default: 'false'
    gpg-private-key:
        description: 'GPG private key to sign the artifacts'
        required: true
runs:
    using: 'composite'
    steps:
      - name: Publish Artifact registry
        run: |
          gcloud artifacts generic upload \
            --project="${{ inputs.gcp-project }}" \
            --location="${{ inputs.registry-location }}" \
            --repository="${{ inputs.registry-repostiory }}" \
            --version="${{ inputs.artifact-version }}" \
            --package="${{ inputs.registry-package }}" \
            --source="${{ inputs.artifact-path }}"
          if [[ "${{ inputs.create-signatures }}" == "true" ]]; then
              echo "${{ inputs.gpg-private-key }}" | gpg --batch --import
              gpg --armor --output ${{ inputs.artifact-path }}.sig --detach-sign ${{ inputs.artifact-path }}
              shasum -a 256 ${{ inputs.artifact-path }} > ${{ inputs.artifact-path }}.sha256
              gpg --armor --sign ${{ inputs.artifact-path }}.sha256
              gcloud artifacts generic upload \
                --location="${{ inputs.registry-location }}" \
                --repository="${{ inputs.registry-repostiory }}" \
                --version=${{ inputs.artifact-version }} \
                --package="${{ inputs.registry-package }}" \
                --source="${{ inputs.artifact-path }}.sig"
              gcloud artifacts generic upload \
                --location="${{ inputs.registry-location }}" \
                --repository="${{ inputs.registry-repostiory }}" \
                --version=${{ inputs.artifact-version }} \
                --package="${{ inputs.registry-package }}" \
                --source="${{ inputs.artifact-path }}.sha256
              gcloud artifacts generic upload \
                --location="${{ inputs.registry-location }}" \
                --repository="${{ inputs.registry-repostiory }}" \
                --version=${{ inputs.artifact-version }} \
                --package="${{ inputs.registry-package }}" \
                --source="${{ inputs.artifact-path }}.sha256.asc""
          fi
 

