---
name: PR

on:
  pull_request:

permissions: {}

jobs:
  format:
    uses: ./.github/workflows/checks.yaml
    with:
      source_branch: ${{ github.head_ref }}
      lint: true
      pre_commit: false
      deps: false
      audit: false
      lint_command: "nix fmt && git diff --exit-code"
    secrets: inherit
