name: PR
on:
  pull_request:
permissions:
  contents: read
jobs:
  format:
    uses: ./.github/workflows/checks.yaml
    with:
      source_branch: ${{ github.event.pull_request.head.sha }}
      pre_commit: false
      deps: false
      audit: false
      lint: true
      lint_command: "nix fmt && git diff --exit-code"
      disable_sudo: false
    secrets: inherit
