name: Download Artifact Registry
description: Download Artifact Registry artifacts
inputs:
    destination:
        description: Destination folder to download the artifact to
        required: false
        default: ./artifacts
    project:
        description: GCP Project name
        required: false
        default: hoprassociation
    region:
        description: GCP region
        required: false
        default: europe-west3
    repository:
        description: Artifact Registry repository name
        required: false
        default: rust-binaries
    package:
        description: Artifact Registry package name
        required: true
    version:
        description: Artifact version to download
        required: true
outputs:
    downloaded_files:
        description: Comma-separated list of downloaded files
        value: ${{ steps.artifacts.outputs.downloaded_files }}
runs:
    using: composite
    steps:
      - name: Download artifacts
        shell: bash
        id: artifacts
        run: |
          # Set gcloud config defaults to avoid repeating flags
          gcloud config set project "${{ inputs.project }}"
          gcloud config set artifacts/location "${{ inputs.region }}"
          gcloud config set artifacts/repository "${{ inputs.repository }}"

          mkdir -p "${{ inputs.destination }}"
          if ! files=$(gcloud artifacts files list \
            --package="${{ inputs.package }}" \
            --version="${{ inputs.version }}" \
            --format=json | jq -r '.[] | .name'); then
            echo "Error: Failed to list artifacts"
            exit 1
          fi
          if [ -z "$files" ]; then
            echo "Error: No files found for package ${{ inputs.package }} version ${{ inputs.version }}"
            exit 1
          fi
          IFS=$'\n' read -rd '' -a files_array <<<"$files" || true
          for file in "${files_array[@]}"; do
            # Extract the filename from the full resource path (after the last ':')
            filename="${file##*:}"
            if ! gcloud artifacts generic download \
              --package="${{ inputs.package }}" \
              --version="${{ inputs.version }}" \
              --destination="${{ inputs.destination }}" \
              --name="${filename}"; then
              echo "Error: Failed to download ${filename}"
              exit 1
            fi
          done
          # Create a comma-separated list of downloaded files
          IFS=','; downloaded_files="${files_array[*]}"; unset IFS
          echo "downloaded_files=$downloaded_files" | tee -a $GITHUB_OUTPUT

